spring.application.name=CebuNest

spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres?
spring.datasource.username=postgres.uwzbxbwnoabdbrwxkatp
spring.datasource.password=kean gwapo123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public


jwt.secret=CebuNestSuperSecretKeyForJWT2026!!
jwt.expiration-ms=86400000
jwt.refresh-expiration-ms=604800000


# SMTP ? fill in your Gmail credentials when ready
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your@gmail.com
spring.mail.password=your-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=815547824139-p54cpobofqe2r9mttbaqs21uu0ci0q8u.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

# Supabase Storage
supabase.url=https://uwzbxbwnoabdbrwxkatp.supabase.co
supabase.anon-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3emJ4Yndub2FiZGJyd3hrYXRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4MTA2OTQsImV4cCI6MjA4NzM4NjY5NH0.Xl_ljpZ9ImFOL3Z9lkPls5TVktcq5R-se1ZPeh_vx7A
supabase.bucket=avatars
